### ISSUE TITLE
Obra icons - Development set up

### ISSUE THREAD

**Issue by Wolfr** [Obra-Studio/obra-icons-mr#1]
(Ideally to be done in september)

* [x] Set up Obra icons correctly in monorepo 
* [x] Connect to Figma file using the Figma Rest API #8
* [x] Pull in the source of the svg files #8
* [x] Process the source to add keywords via ChatGPT #8
* [x] [@ghostdevv] Build a filter like on https://icons.mono.company/ to filter on icon name and keywords #10
* [x] [@ghostdevv] Be able to download and copy the SVG like on above website ec1b830d6248014698285fdc5098ec23da9be2f9
* [x] The data is used to be able to generate a dev package #8
* [x] [J] Change domain to https://icons.obra.studio/ so and deploy to Cloudflare pages
